In [1]:
import numpy as np

In [2]:
# 1) Create an array of 10 zeros

a = np.zeros(10)
a

array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0.])

In [3]:
# 2)Create an array of 10 ones

b= np.ones(10)

In [4]:
b

array([1., 1., 1., 1., 1., 1., 1., 1., 1., 1.])

In [5]:
# 3) Create an array of 10 fives

c=np.ones(10)
c

array([1., 1., 1., 1., 1., 1., 1., 1., 1., 1.])

In [6]:
# used Broadcasting
c*5

array([5., 5., 5., 5., 5., 5., 5., 5., 5., 5.])

In [7]:
# 4) Create an array of the integers from 10 to 50

d = np.arange(10,50)
d

array([10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26,
       27, 28, 29, 30, 31, 32, 33, 34, 35, 36, 37, 38, 39, 40, 41, 42, 43,
       44, 45, 46, 47, 48, 49])

In [8]:
# 5) Create an array of all the even integers from 10 to 50

arr= np.arange(10,50,2)
arr

array([10, 12, 14, 16, 18, 20, 22, 24, 26, 28, 30, 32, 34, 36, 38, 40, 42,
       44, 46, 48])

In [9]:
# 6) Create a 3x3 matrix with values ranging from 0 to 8

arr = np.arange(0,9)
arr

array([0, 1, 2, 3, 4, 5, 6, 7, 8])

In [10]:
arr.reshape(3,3)

array([[0, 1, 2],
       [3, 4, 5],
       [6, 7, 8]])

In [11]:
# 7) Use NumPy to generate a random number between 0 and 1

arr = np.random.uniform(0,1, size=1)
arr

array([0.69666616])

In [12]:
# 8)Use NumPy to generate an array of 25 random numbers sampled from a standard normal distribution

arr=np.random.randn(5,5)
arr

array([[-1.52914396, -1.49854662, -1.70986433, -1.35672428,  1.21161413],
       [ 0.82549346, -0.18719266, -0.13408463, -0.1304255 , -2.27210919],
       [-0.6960424 , -0.26066148,  1.04339355,  0.36001639,  0.19653786],
       [-0.34848669, -0.31466436,  0.77649901,  0.34531675,  1.04978733],
       [ 0.84001438, -1.35780692,  0.17699802, -0.95399605, -0.16561939]])

In [13]:
arr.ndim

2

In [14]:
# 9)Create an array of 20 linearly spaced points between 0 and 1:

arr = np.random.rand(4,5)
arr

array([[0.48805307, 0.78598795, 0.7637655 , 0.42081546, 0.8584404 ],
       [0.72793872, 0.28944926, 0.03094713, 0.37461576, 0.27602315],
       [0.69530442, 0.04333119, 0.81408399, 0.88549985, 0.34439565],
       [0.55808469, 0.51153372, 0.56692951, 0.0466971 , 0.44388787]])

In [15]:
# 10) Get the sum of all the values in mat

arr = np.arange(0,25).reshape(5,5)
arr

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24]])

In [16]:
arr.sum()

300

In [17]:
# 11) how to create 1D Array ?

num=[1,2,3]
arr=np.array(num)
arr

array([1, 2, 3])

In [18]:
# 12) How to create 2D Array ?

num = [[1,2,3,4,5], [6,7,8,9,0]]
arr = np.array(num)
arr

array([[1, 2, 3, 4, 5],
       [6, 7, 8, 9, 0]])

In [19]:

num = [[[1,2,3,4,5],[6,7,8,9,0],[3,6,4,6,7]]]
arr = np.array(num)
arr

array([[[1, 2, 3, 4, 5],
        [6, 7, 8, 9, 0],
        [3, 6, 4, 6, 7]]])

In [20]:
# 14) how to identified datatyp for numpy array?

arr.dtype

dtype('int32')

In [21]:
# 15) Print 1D array with 5 zeros.

arr = np.zeros(5)
arr

array([0., 0., 0., 0., 0.])

In [22]:
# 16) print zeros with 2 rows and 3 columns ?

arr = np.zeros((2,3))
arr

array([[0., 0., 0.],
       [0., 0., 0.]])

In [23]:
# 17) Create array with eye() - diagonal values ?

arr = np.eye(5)
arr

array([[1., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0.],
       [0., 0., 1., 0., 0.],
       [0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 1.]])

In [24]:
# 18) use of diag() square matrix ?

arr = np.diag([1,2,3,4])
arr

array([[1, 0, 0, 0],
       [0, 2, 0, 0],
       [0, 0, 3, 0],
       [0, 0, 0, 4]])

In [25]:
# 19) Print Range Between 1 To 15 and show 4 integers random numbers

arr = np.random.randint(1,15, size =4)
arr

array([ 9, 12,  7, 12])

In [26]:
arr =np.random.seed(123)
arr

In [27]:
# 20) Print first position, last position and 2nd and 3rd position

num = [2,4,6,7,9,56,26,45,89]

arr = np.array(num)
arr

array([ 2,  4,  6,  7,  9, 56, 26, 45, 89])

In [28]:
arr[0]

2

In [29]:
arr[-1]

89

In [30]:
arr[1]

4

In [31]:
arr[2]

6

In [32]:
# 21)create a matrix 3 * 3 with value ranging from 0 to 8

arr = np.arange(0,9).reshape(3,3)
arr

array([[0, 1, 2],
       [3, 4, 5],
       [6, 7, 8]])

In [33]:
# 22) create matrix 2 * 2 with value ranging from 1 to 4

arr = np.arange(1,5).reshape(2,2)
arr

array([[1, 2],
       [3, 4]])

In [34]:
# 23) print random number from 0 to 1

arr = np.random.rand(2,2)
arr

array([[0.69646919, 0.28613933],
       [0.22685145, 0.55131477]])

In [35]:
# 24) print size of num array

arr.size

4

In [36]:
# 25) create an array of 20 linearly spaced point between 0 to 1

arr = np.linspace(0,1,20)

In [37]:
arr

array([0.        , 0.05263158, 0.10526316, 0.15789474, 0.21052632,
       0.26315789, 0.31578947, 0.36842105, 0.42105263, 0.47368421,
       0.52631579, 0.57894737, 0.63157895, 0.68421053, 0.73684211,
       0.78947368, 0.84210526, 0.89473684, 0.94736842, 1.        ])

In [38]:
arr.sort()

In [39]:
arr

array([0.        , 0.05263158, 0.10526316, 0.15789474, 0.21052632,
       0.26315789, 0.31578947, 0.36842105, 0.42105263, 0.47368421,
       0.52631579, 0.57894737, 0.63157895, 0.68421053, 0.73684211,
       0.78947368, 0.84210526, 0.89473684, 0.94736842, 1.        ])

In [40]:
# 26)Use of sort() function ?

num = [[6,3,8,5,6],[9,5,11,15,8]]
arr = np.array(num)
arr

array([[ 6,  3,  8,  5,  6],
       [ 9,  5, 11, 15,  8]])

In [41]:
arr1 = np.sort(arr)
arr1

array([[ 3,  5,  6,  6,  8],
       [ 5,  8,  9, 11, 15]])

In [43]:
# 27) How to get the positions where elements of two arrays match?

a = np.array([1,2,3,5,7,8,8,5,4])
b = np.array([5,3,7,9,2,4,5,7,8])

c=np.where(a==b)
print(c)

(array([], dtype=int64),)


In [47]:
# 28)Create a Numpy array filled with all zeros

arr = np.zeros([3,3], dtype= int)
arr

array([[0, 0, 0],
       [0, 0, 0],
       [0, 0, 0]])

In [48]:
arr = np.zeros(4)
arr

array([0., 0., 0., 0.])

In [49]:
print([1,2,3,4,5,6,7] in arr.tolist())

False


In [50]:
print([16,17,20,19,18] in arr.tolist())

False


In [51]:
print([0,0,0,0] in arr.tolist())

False


In [55]:
# 30)Write a NumPy program to convert a list of numeric value into a one-dimensional NumPy array.

a = [2,5,8,6,5,4,3]

arr = np.array(a)
arr

array([2, 5, 8, 6, 5, 4, 3])

In [56]:
# 31)Write a NumPy program to create a 5x5 array with random values and find the minimum and maximum values.

arr = np.random.rand(5,5)
arr

array([[0.71946897, 0.42310646, 0.9807642 , 0.68482974, 0.4809319 ],
       [0.39211752, 0.34317802, 0.72904971, 0.43857224, 0.0596779 ],
       [0.39804426, 0.73799541, 0.18249173, 0.17545176, 0.53155137],
       [0.53182759, 0.63440096, 0.84943179, 0.72445532, 0.61102351],
       [0.72244338, 0.32295891, 0.36178866, 0.22826323, 0.29371405]])

In [58]:
arr.max()

0.9807641983846155

In [59]:
arr.min()

0.05967789660956835

In [61]:
# 32)Write a NumPy program to compute the multiplication of two given matrixes. Sample Matrix: [[1, 0], [0, 1]] [[1, 2], [3, 4]]

a = [[1,0], [0,1]]
b = [[1,2], [3,4]]

print(a)
print(b)

result = np.dot(a,b)
print(result)



[[1, 0], [0, 1]]
[[1, 2], [3, 4]]
[[1 2]
 [3 4]]


In [63]:
# 33)Create a two-dimensional array with the flattened input as a diagona

a = np.diag([[1,2,3], [4,5,6]])
a

array([1, 5])

In [66]:
# 34)Write a NumPy program to compute the sum of the diagonal element of a given array.

a = np.arange(6).reshape(3,2)
a

array([[0, 1],
       [2, 3],
       [4, 5]])

In [67]:
a.trace()

3

In [68]:
# 35)Use of around() function: returns a decimal value rounded to a desired position of the decimal

arr = np.array([23.008, 25.678, 22.45, 16.4])
arr

array([23.008, 25.678, 22.45 , 16.4  ])

In [69]:
np.around(arr,2)

array([23.01, 25.68, 22.45, 16.4 ])